# This is a basic workflow to help you get started with Actions

name: buildJar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        java: [17] 
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.head_commit.message, '[no ci]')
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Release to GitHub
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            libs/*.jar
            !libs/*-dev.jar
            !libs/*-sources.jar
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: "[BUILD]"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          removeArtifacts: true
          allowUpdates: true
          artifacts: "libs/*.jar"
          artifactContentType: application/java-archive
